exp:
  mode: rave
  exp_name: rave
  save_dir: ./

data:
  backlit_images_path: ./train_data/BAID/train/backlit/
  welllit_images_path: ./train_data/DIV2K/
    
train:
  num_epochs: 3000
  num_workers: 4

  unet_model:
    thr_loss: 90
    lr: 0.00002
    weight_decay: 0.001
    num_reconstruction_iters: 1000
    batch_size: 8
    display_iter: 20
    load_pretrain: False
    pretrain_dir: ''

guidance:
  remove_first_n_tokens: 0
